module.exports = {
    sdvx: {
        "booth": "BOOTH",
        "inf": "-infinite infection-",
        "gw": "GRAVITY WARS",
        "heaven": "HEAVENLY HAVEN",
        "vivid": "VIVID WAVE",
        "exceed": "EXCEED GEAR",
        "konaste": "Konaste"
    },
    iidx: {
        "inf": "INFINITAS",
        "1": "1st style",
        "sub": "substream",
        "2": "2nd style",
        "3": "3rd style",
        "4": "4th style",
        "5": "5th style",
        "6": "6th style",
        "7": "7th style",
        "8": "8th style",
        "9": "9th style",
        "10": "10th style",
        "11": "11 IIDX RED",
        "12": "HAPPY SKY",
        "13": "DistorteD",
        "14": "GOLD",
        "15": "DJ TROOPERS",
        "16": "EMPRESS",
        "17": "SIRIUS",
        "18": "Resort Anthem",
        "19": "Lincle",
        "20": "tricoro",
        "21": "SPADA",
        "22": "PENDUAL",
        "23": "copula",
        "24": "SINOBUZ",
        "25": "CANNON BALLERS",
        "26": "ROOTAGE",
        "27": "HEROIC VERSE",
        "28": "BISTROVER",
        "29": "CastHour",
        "30": "RESIDENT",
        "31": "EPOLIS",
        "32": "Pinky Crush",
        "inf2020": "Infinitas",
        default: "Removed"
    },
    chuni: {
        "chuni": "CHUNITHM",
        "chuniplus": "CHUNITHM PLUS",
        "air": "AIR",
        "airplus": "AIR PLUS",
        "star": "STAR",
        "starplus": "STAR PLUS",
        "amazon": "AMAZON",
        "amazonplus": "AMAZON PLUS",
        "crystal": "CRYSTAL",
        "crystalplus": "CRYSTAL PLUS",
        "paradise": "PARADISE",
        "paradiselost": "PARADISE LOST",
        "new": "NEW",
        "newplus": "NEW PLUS",
        "sun": "SUN",
        "sunplus": "SUN PLUS",
        "luminous": "LUMINOUS"
    },
    jubeat: {
        "jubeat": "jubeat",
        "ripples": "ripples",
        "knit": "knit",
        "copious": "copious",
        "saucer": "saucer",
        "prop": "prop",
        "qubell": "Qubell",
        "clan": "clan",
        "festo": "festo",
        "ave": "Ave."
    }
}